# Generated by Django 5.0.6 on 2024-05-27 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ArtistName', models.CharField(blank=True, max_length=150, null=True)),
                ('Nationality', models.CharField(blank=True, max_length=150, null=True)),
                ('DateOfBirth', models.DateField()),
                ('DateOfDeath', models.DateField()),
                ('PrimaryMedium', models.CharField(blank=True, max_length=150, null=True)),
                ('Education', models.CharField(blank=True, max_length=50, null=True)),
                ('AwardsExhibitions', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Artists',
            },
        ),
        migrations.CreateModel(
            name='Brushshape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brushshape', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'BrushShapes',
            },
        ),
        migrations.CreateModel(
            name='Finish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finish', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Finish',
            },
        ),
        migrations.CreateModel(
            name='Ground',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ground', models.CharField(blank=True, max_length=150, null=True)),
                ('underlayer', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Grounds',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Manufacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CreationYear', models.IntegerField(blank=True, null=True)),
                ('CreationMonth', models.CharField(choices=[('jan', 'jan'), ('feb', 'feb'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec'), ('NA', 'NA')], max_length=3)),
                ('CreationDay', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('NA', 'NA')], max_length=2)),
                ('PlaceofManufacture', models.CharField(blank=True, max_length=250, null=True)),
                ('SeasonofManufacture', models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn', 'Autumn'), ('Winter', 'Winter'), ('NA', 'NA')], max_length=10)),
                ('Orientation', models.CharField(choices=[('Inside', 'Inside'), ('Outside', 'Outside'), ('NA', 'NA')], max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Manufacture',
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Movements',
            },
        ),
        migrations.CreateModel(
            name='SupportType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Types',
            },
        ),
        migrations.CreateModel(
            name='Technique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('technique', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'Techniques',
            },
        ),
        migrations.CreateModel(
            name='Underdrawingmaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('underdrawingmaterial', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name_plural': 'UnderdrawingMaterials',
            },
        ),
        migrations.CreateModel(
            name='pigment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ColorIndex', models.CharField(blank=True, max_length=50, null=True)),
                ('subgroup', models.CharField(blank=True, max_length=50, null=True)),
                ('Name', models.CharField(blank=True, max_length=150, null=True)),
                ('OrganicChoices', models.CharField(choices=[('organic', 'synthetic'), ('NA', 'NA')], max_length=10)),
                ('ASTM_Rating', models.CharField(blank=True, max_length=10, null=True)),
                ('Remarks', models.TextField(blank=True, null=True)),
                ('UsedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.artist')),
            ],
            options={
                'verbose_name_plural': 'Pigments',
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=150, null=True)),
                ('Title_en', models.CharField(blank=True, max_length=150, null=True)),
                ('Category', models.CharField(blank=True, max_length=150, null=True)),
                ('Currentlocation', models.CharField(blank=True, max_length=150, null=True)),
                ('Currentowner', models.CharField(blank=True, max_length=150, null=True)),
                ('Dimension', models.CharField(blank=True, max_length=150, null=True)),
                ('OriginalOrCopy', models.CharField(choices=[('Original', 'Original'), ('Copy', 'Copy'), ('NA', 'NA')], max_length=150)),
                ('Seies', models.CharField(blank=True, max_length=150, null=True)),
                ('DecayStatus', models.ImageField(blank=True, null=True, upload_to='')),
                ('Description', models.TextField(blank=True, null=True)),
                ('Artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.artist')),
                ('Brushshape', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.brushshape')),
                ('Finish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.finish')),
                ('Ground', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.ground')),
                ('Manufacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.manufacture')),
                ('Movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.movement')),
                ('Pigment', models.ManyToManyField(blank=True, null=True, to='ArtWork.pigment')),
                ('SupportType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.supporttype')),
                ('Technique', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.technique')),
                ('Underdrawingmaterial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtWork.underdrawingmaterial')),
            ],
            options={
                'verbose_name_plural': 'Artworks',
            },
        ),
    ]
