# Generated by Django 5.0.6 on 2024-05-27 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='Pigment',
            field=models.ManyToManyField(blank=True, to='ArtWork.pigment'),
        ),
    ]
