# Generated by Django 5.0.6 on 2024-05-27 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0003_alter_artwork_decaystatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pigment',
            name='OrganicChoices',
            field=models.CharField(choices=[('organic', 'organic'), ('synthetic', 'synthetic'), ('NA', 'NA')], max_length=10),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='UsedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.artist'),
        ),
    ]
