# Generated by Django 5.0.6 on 2024-05-27 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0004_alter_pigment_organicchoices_alter_pigment_usedby'),
    ]

    operations = [
        migrations.AddField(
            model_name='pigment',
            name='Found_In',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='pigment',
            name='Source',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
