# Generated by Django 5.0.6 on 2024-05-29 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0007_alter_image_options_artwork_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='Brushshape',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.brushshape'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='Finish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.finish'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='Manufacture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.manufacture'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='Movement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.movement'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='OriginalOrCopy',
            field=models.CharField(blank=True, choices=[('Original', 'Original'), ('Copy', 'Copy'), ('NA', 'NA')], max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='SupportType',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.supporttype'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='Technique',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.technique'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='Underdrawingmaterial',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.underdrawingmaterial'),
        ),
    ]
