# Generated by Django 5.0.6 on 2024-05-29 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0008_alter_artwork_brushshape_alter_artwork_finish_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='Ground',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='ArtWork.ground'),
        ),
    ]
