# Generated by Django 5.0.6 on 2024-05-29 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0009_alter_artwork_ground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='SeasonofManufacture',
            field=models.CharField(choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn(Fall)', 'Autumn(Fall)'), ('Winter', 'Winter'), ('NA', 'NA')], max_length=20),
        ),
    ]
