# Generated by Django 5.0.6 on 2024-05-29 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0010_alter_manufacture_seasonofmanufacture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manufacture',
            name='CreationDay',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27'), ('28', '28'), ('29', '29'), ('30', '30'), ('31', '31'), ('NA', 'NA')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='CreationMonth',
            field=models.CharField(blank=True, choices=[('jan', 'jan'), ('feb', 'feb'), ('mar', 'mar'), ('apr', 'apr'), ('may', 'may'), ('jun', 'jun'), ('jul', 'jul'), ('aug', 'aug'), ('sep', 'sep'), ('oct', 'oct'), ('nov', 'nov'), ('dec', 'dec'), ('NA', 'NA')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='Orientation',
            field=models.CharField(blank=True, choices=[('Inside', 'Inside'), ('Outside', 'Outside'), ('NA', 'NA')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='manufacture',
            name='SeasonofManufacture',
            field=models.CharField(blank=True, choices=[('Spring', 'Spring'), ('Summer', 'Summer'), ('Autumn(Fall)', 'Autumn(Fall)'), ('Winter', 'Winter'), ('NA', 'NA')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='pigment',
            name='OrganicChoices',
            field=models.CharField(blank=True, choices=[('organic', 'organic'), ('synthetic', 'synthetic'), ('NA', 'NA')], max_length=10, null=True),
        ),
    ]
