# Generated by Django 5.0.6 on 2024-05-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtWork', '0011_alter_manufacture_creationday_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='image_1',
        ),
        migrations.AddField(
            model_name='image',
            name='image_2',
            field=models.ImageField(blank=True, default='default.jpg', null=True, upload_to=''),
        ),
    ]
